### ISSUE TITLE
Report when productions are collapsed

### ISSUE THREAD

**Issue by bterlson** [rbuckton/grammarkdown#15]
Can emu emitter emit the a collapsed attribute on emu-prodref when the production is collapsed, ie where the prudction name and only rhs are on the same line?

**Comment by rbuckton** [comment]
@bterlson I'm not clear on the ask here. Do you want me to write a `collapsed` attribute when I write out an `emu-production`? I don't think I emit an `emu-prodref` anywhere in the ecmarkup emitter currently.

**Comment by rbuckton** [comment]
ping @bterlson. Do you still need this?

**Comment by bterlson** [comment]
Yes! Collapsed attribute on emu-production is what OP means :-P
