### ISSUE TITLE
Support parsing grammar fragments

### ISSUE THREAD

**Issue by bterlson** [rbuckton/grammarkdown#16]
It would be great to support parsing of fragments along the lines of `NonTerminal`, `Initializer?`, and `Pattern[U]`. This would allow `<emu-grammar>` to be used universally for full productions and references (and Emd could get out of the business of parsing the contents inside of pipes).

All of the above cases should emit a <emu-nt> element with the appropriate attributes (none, optional, and params="U" respectively).

**Comment by rbuckton** [comment]
Should a fragment be emit inside of an `<emu-rhs>` or should it only emit the contents?

**Comment by rbuckton** [comment]
ping @bterlson. Do you still need this?

**Comment by bterlson** [comment]
Let's wait on this. Post snapshot I am going to make significant changes around handling of pipes, may impact what we do here.

**Comment by rbuckton** [comment]
@bterlson, @bakkot: Can I close this or is this still something needed by ecmarkup?

**Comment by bakkot** [comment]
The current state affairs is that ecmarkdown handles [parsing](https://github.com/tc39/ecmarkdown/blob/d0ade878a09521bc713c6ff4e36474d70a7f2dcd/src/parser.ts#L435-L451) and [emitting](https://github.com/tc39/ecmarkdown/blob/d0ade878a09521bc713c6ff4e36474d70a7f2dcd/src/emitter.ts#L148-L160) fragments as in the OP, which works fine even if it is a little redundant with grammarkdown. I have no plans to change the implementation.

I think this can be closed.
