### ISSUE TITLE
Feature request: multiple grammar parameter constraints on the RHS

### ISSUE THREAD

**Issue by littledan** [rbuckton/grammarkdown#25]
In the [RegExp named groups proposal](https://github.com/tc39/proposal-regexp-named-groups), I'm updating the "Annex B" grammar for this new feature. I wanted to make the right hand side of a grammar production depend on two parameters, not one, but this seems to be not accounted for in Grammarkdown. Specifically, in the code, it looks like `parseParameterValueAssertionTail` expects a single token, and then a closing square bracket, but here, I'd have multiple comma-separated tokens. cc @bterlson 

Anyway, this is not urgent; it can be worked around by separating into another nonterminal, [as I did here](https://tc39.github.io/proposal-regexp-named-groups/#prod-SourceCharacterIdentityEscape).

**Comment by rbuckton** [comment]
Fixed in bc0d8172cb4a9b84960b3f79a2f7d3c034f57c5c.

**Comment by littledan** [comment]
Thanks!
