### ISSUE TITLE
Support <ins>/<del> tags in more places in grammars

### ISSUE THREAD

**Issue by littledan** [rbuckton/grammarkdown#26]
In ECMAScript spec proposals, we use `<ins>` and `<del>` HTML tags when marking changes vs current spec text. In a grammarkdown grammar, I noticed that things like the following trip this up:

```
Foo ::
  [~U] <ins>foo</ins>
```

Somehow `<ins>` is escaped and rendered inside the `[~U]`. The tags are well-supported in many other places in grammars, however. cc @bterlson

**Comment by rbuckton** [comment]
Fixed in 7b6db4d39fc2597aac05d4f4bbe20da56971a0b8.

**Comment by littledan** [comment]
Thank you!
