### ISSUE TITLE
Copying and pasting rendered grammar leads to missing spaces

### ISSUE THREAD

**Issue by littledan** [rbuckton/grammarkdown#27]
Low-priority feature request: Include the spaces.

**Comment by rbuckton** [comment]
@littledan, is this happening when rendering via ecmarkup? Do you have an example/repro you can share?

**Comment by littledan** [comment]
Yes, it's through ecmarkup, so I may be mistaken about the root cause. As an example, look at https://tc39.github.io/ecma262/#prod-PropertyDefinitionList . Copying that whole definition yields, PropertyDefinitionList[Yield, Await]:
PropertyDefinition[?Yield, ?Await]
PropertyDefinitionList[?Yield, ?Await],PropertyDefinition[?Yield, ?Await]

**Comment by rbuckton** [comment]
cc: @bakkot. Since I don't have contributor rights to ecmarkup I can't transfer this issue.

**Comment by rbuckton** [comment]
Moved to https://github.com/tc39/ecmarkup/issues/248
