### ISSUE TITLE
Do not do file I/O to read the grammars

### ISSUE THREAD

**Issue by domenic** [rbuckton/grammarkdown#28]
The grammar.ts file does require.resolve and fs.readFileSync to read some grammars.

This is unfortunate as it prevents grammarkdown, and thus ecmarkup, from being run inside the browser.

This is unfortunate because I am trying to turn compilation of the ECMAScript specification into a benchmark.

Ideally some build process would convert these grammars into template strings that could be require()ed directly, I think.

**Comment by rbuckton** [comment]
Fixed in 7b6db4d39fc2597aac05d4f4bbe20da56971a0b8. The new `Host` API allows you more control over built-in grammars and file I/O.
