### ISSUE TITLE
Add support for ins and del tags for new grammar rules

### ISSUE THREAD

**Issue by sirisian** [rbuckton/grammarkdown#33]
This is another continuation of #26 to add more support for ```<ins>``` and ```<del>``` tags in the grammar.

This output looks bad and for a new rule probably isn't how someone would write it:
```xml
<emu-grammar>
  <ins>MemberDefinition :</ins>
    <ins>PropertyName ColonType? Initializer?</ins>
</emu-grammar>
```
```xml
<ins>
  <emu-production name="MemberDefinition" id="prod-MemberDefinition">
    <emu-nt><a href="#prod-MemberDefinition">MemberDefinition</a></emu-nt>
    <emu-geq>:</emu-geq>
    <ins>
      <emu-rhs a="7149f9b7">
        <emu-nt id="_ref_11734"><a href="#prod-PropertyName">PropertyName</a></emu-nt>
        <emu-nt optional="" id="_ref_11735">
          <a href="#prod-ColonType">ColonType</a>
          <emu-mods>
            <emu-opt>opt</emu-opt>
          </emu-mods>
        </emu-nt>
        <emu-nt optional="" id="_ref_11736">
          <a href="#prod-Initializer">Initializer</a>
          <emu-mods>
            <emu-opt>opt</emu-opt>
          </emu-mods>
        </emu-nt>
      </emu-rhs>
    </ins>
  </emu-production>
</ins>
```
The following look close. (Both generate the same output) The first is probably how I'd write new rules to wrap it all in an ```<ins>```:
```xml
<emu-grammar>
  <ins>MemberDefinition :
    PropertyName ColonType? Initializer?</ins>
</emu-grammar>
```

```xml
<emu-grammar>
  <ins>MemberDefinition :</ins>
    PropertyName ColonType? Initializer?
</emu-grammar>
```

```xml
<ins>
  <emu-production name="MemberDefinition" id="prod-MemberDefinition">
    <emu-nt><a href="#prod-MemberDefinition">MemberDefinition</a></emu-nt>
    <emu-geq>:</emu-geq>
    <emu-rhs a="7149f9b7">
      <emu-nt id="_ref_11734"><a href="#prod-PropertyName">PropertyName</a></emu-nt>
      <emu-nt optional="" id="_ref_11735">
        <a href="#prod-ColonType">ColonType</a>
        <emu-mods>
          <emu-opt>opt</emu-opt>
        </emu-mods>
      </emu-nt>
      <emu-nt optional="" id="_ref_11736">
        <a href="#prod-Initializer">Initializer</a>
        <emu-mods>
          <emu-opt>opt</emu-opt>
        </emu-mods>
      </emu-nt>
    </emu-rhs>
  </emu-production>
</ins>
```
This is bad because of how: <emu-prodref name=MemberDefinition></emu-prodref> works for the appendix. It copies and pastes the emu-production and the ```<ins>``` is outside of it and doesn't get copied so when scrolling through the appendix you don't see any green tint over the new rule.

This is how it should(?) look and it renders correctly in ecmarkup:
```xml
<emu-production name="MemberDefinition" id="prod-MemberDefinition">
  <ins>
    <emu-nt><a href="#prod-MemberDefinition">MemberDefinition</a></emu-nt>
    <emu-geq>:</emu-geq>
    <emu-rhs a="7149f9b7">
      <emu-nt id="_ref_11734"><a href="#prod-PropertyName">PropertyName</a></emu-nt>
      <emu-nt optional="" id="_ref_11735">
        <a href="#prod-ColonType">ColonType</a>
        <emu-mods>
          <emu-opt>opt</emu-opt>
        </emu-mods>
      </emu-nt>
      <emu-nt optional="" id="_ref_11736">
        <a href="#prod-Initializer">Initializer</a>
        <emu-mods>
          <emu-opt>opt</emu-opt>
        </emu-mods>
      </emu-nt>
    </emu-rhs>
  </ins>
</emu-production>
```

**Comment by rbuckton** [comment]
```grammarkdown
<ins>A :</ins>
  B
```

Doesn't really work to only highlight the production name, due to the output ecmarkup expects. Consider the following:

**grammarkdown (input)**
```grammarkdown
A :
  B
```

**ecmarkup (output)**
```html
<emu-production name="A">
    <emu-rhs a="ae4f281d"><emu-nt>B</emu-nt></emu-rhs>
</emu-production>
```

If you just want an `<ins>` around the production name, there's nowhere to put it because the name is embedded in the `name` attribute of the `<emu-production>`. As a result, the `<ins>` goes before the entire production, but the trailing `</ins>` becomes lost. I may need to make it an error to have any closing tags between the start of the production name and start of any right-hand-side, but html tags aren't actually part of grammarkdown proper, so right now what I do is a best effort.

There's also no way to put an `<ins></ins>` around something like a production parameter as those are also embedded in an HTML attribute.

**Comment by rbuckton** [comment]
I've created #55 to make it clearer that this is an error. 

@bakkot any thoughts on ways of marking parts of a production header with `<ins>`/`<del>` (like a new/removed production parameter)?

**Comment by bakkot** [comment]
@rbuckton Hm. Yeah, that's something which could and probably should work, but I'm not going to prioritize support for it in the near future. Opened https://github.com/tc39/ecmarkup/issues/250 to track, though.
