### ISSUE TITLE
Mixed content warning in TypeScript example

### ISSUE THREAD

**Issue by mikesamuel** [rbuckton/grammarkdown#34]
In the README, &para; [Examples](https://github.com/rbuckton/grammarkdown#examples), the link to the HTML for the TypeScript grammar is broken because the CSS is loaded via http instead of https.

Viewed in modern Chrome, I get the below in the dev console.

> Mixed Content: The page at 'https://rbuckton.github.io/grammarkdown/typescript.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://bterlson.github.io/ecmarkup/elements.css'. This request has been blocked; the content must be served over HTTPS.

<img width="1399" alt="Screen Shot 2019-10-01 at 3 25 46 PM" src="https://user-images.githubusercontent.com/368886/65993712-c3d43080-e45f-11e9-8adf-3dd5c2239ec9.png">

**Comment by rbuckton** [comment]
Should be fixed. At some point I had removed the part where I built the examples, but that has been added back into the docs build. The TypeScript example currently returns a 404, but that should change once github's CDN realizes the file actually exists.
