### ISSUE TITLE
RHS IDs

### ISSUE THREAD

**Issue by bterlson** [rbuckton/grammarkdown#4]
There needs to be a way for consumers to reference a particular RHS alternative of a production. This is done all over ECMAScript specifications where all the syntax for a feature is defined at the start of the clause and subsequent subclauses define semantics for specific alternatives of the productions.

Emu supports this via an `a` attribute on `emu-rhs` allowing authors to specify an alternative id that can remain stable across spec versions and won't get hosed by refactoring or modifying the grammar. Something similar can be considered for grammarkdown, eg.

```
BindingIdentifier ::
    Identifier       #a
    [~Yield] `yield` #b
```

**Comment by rbuckton** [comment]
Added in 03b7ea4.

**Comment by bterlson** [comment]
Can you NPM publish?
