### ISSUE TITLE
Request: warn for unused parameters

### ISSUE THREAD

**Issue by bakkot** [rbuckton/grammarkdown#46]
Currently there is no warning given for

```
Foo[A] ::
  Bar[+A]

Bar[A] ::
  `x`
```

I think it would be useful to have warnings for both of these, since neither nonterminal ever actually uses its parameter in any of its productions.

This only really makes sense as a warning if you know you're processing the entire grammar, rather than just some subset of it (because if you are only processing part of it, there could be another production elsewhere which does use the parameter). Perhaps there could be an argument to the checker telling it to make this assumption?

**Comment by rbuckton** [comment]
I'll look into this. Currently the grammar checker checks a single file at a time, but a check like this requires knowledge of the whole grammar (across multiple files), since `Foo[A]` could have also been defined in another file that *does* reference `A` (and we generally want all productions to agree WRT parameter count).

**Comment by bakkot** [comment]
> Currently the grammar checker checks a single file at a time, but a check like this requires knowledge of the whole grammar (across multiple files)

Ah, neat. That would be useful to me anyway - I was planning on making a Host which represented each `Syntax` section in ECMA262 as its own file (vs just concatenating them all and representing that as a single file), because that makes it simpler to map line numbers reported by grammarkdown's diagnostics to line numbers in the actual input file, but I didn't realize that might have an effect on the diagnostics apart from line numbers.

**Comment by rbuckton** [comment]
>  I was planning on making a Host which represented each `Syntax` section in ECMA262 as its own file [...]

I started doing something similar in some work I was doing for `ecmarkup-vscode`, emulating VSCode's mixed document parsing for embedded content. It essentially tracks the start/end offsets within a document at which a different language mode is found (such as inside of `<script>` tags in an HTML document). My implementation essentially generates a source map for the extracted content that can be used to map diagnostics back to their original locations.

![Annotation 2020-04-12 200056](https://user-images.githubusercontent.com/3902892/79088984-3a989300-7cf9-11ea-8c04-b100bf8ef342.png)

**Comment by bakkot** [comment]
Nice! I'm doing it a little more haphazardly for now, since I'm really only worried about mapping errors back to their source.

```js
let lintWalker = document.createTreeWalker(document.body, 1 /* elements */);

let grammarNodes: Node[] = [];
let grammarParts: string[] = [];
let grammarStartOffsets: number[] = [];
let grammarLineOffsets: number[] = [];

function lintWalk() {
  let node: Element = (lintWalker.currentNode as Element);
  if (node.nodeName === 'EMU-ANNEX' && node.id === 'sec-additional-ecmascript-features-for-web-browsers') {
    // for now, don't worry about linting annex B.
    // this is mostly so we don't have to deal with having two inconsistent copies of some of the grammar productions.
    return;
  }

  if (node.nodeName === 'EMU-GRAMMAR') {
    if (node.getAttribute('type') === 'definition') {
      let loc = getLocation(dom, node);
      let start = loc.startTag.endOffset;
      let end = loc.endTag.startOffset;
      grammarStartOffsets.push(start);
      grammarLineOffsets.push(loc.startTag.line);
      let realSource = sourceText!.slice(start, end);
      grammarParts.push(realSource);
      grammarNodes.push(node);
    }
  }

  let firstChild = lintWalker.firstChild();
  if (firstChild) {
    while (true) {
      lintWalk();
      let next = lintWalker.nextSibling();
      if (!next) break;
    }
    lintWalker.parentNode();
  }
}
lintWalk();

let parser = new Parser();
let fakeHost: SyncHost = {
  readFileSync(file: string) {
    let idx = parseInt(file);
    if (idx.toString() !== file || idx < 0 || idx >= grammarParts.length) {
      throw new Error('tried to read non-existent ' + file);
    }
    return grammarParts[idx];
  },
  resolveFile(file: string) {
    return file;
  },
  normalizeFile(file: string) {
    return file;
  },
  getSourceFileSync(file: string) {
    return parser.parseSourceFile(file, this.readFileSync(file));
  },
} as any; // good enough! todo maybe ask rbuckton for better types
let compilerOptions = {
  format: EmitFormat.ecmarkup,
  noChecks: false,
  noUnusedParameters: true,
};
let grammar = new GrammarFile(Object.keys(grammarParts), compilerOptions, fakeHost);
grammar.parseSync();
grammar.checkSync();

if (grammar.diagnostics.size > 0) {

  // `detailedMessage: false` prevents prepending line numbers, which is good because we're going to make our own
  let errors = grammar.diagnostics.getDiagnosticInfos({ formatMessage: true, detailedMessage: false }).map(m => {
    let idx = +m.sourceFile!.filename;
    let trueLocation = grammarStartOffsets[idx] + m.pos;
    let trueLine = grammarLineOffsets[idx] + m.range!.start.line;
    let trueCol = m.range!.start.character + 1; // column numbers are traditionally one-based
    return `${path}:${trueLine}:${trueCol}: ${m.formattedMessage}`;
  });
  console.error(chalk.underline('Grammar errors:') + '\n' + errors.join('\n') + '\n');
  throw new Error('There were grammar-sanity errors.');
}
```

**Comment by rbuckton** [comment]
To create a host you could do this:
```ts
let fakeHost = new SyncHost({ 
  useBuiltinGrammars: false,
  ignoreCase: false,
  readFileSync: file =>
    let idx = parseInt(file);
    if (idx.toString() !== file || idx < 0 || idx >= grammarParts.length) {
      throw new Error('tried to read non-existent ' + file);
    }
    return grammarParts[idx];
  },
  writeFileSync: false
});
```

The only thing that might be missing is having control over file resolution (currently it uses Node's `path` module.

**Comment by bakkot** [comment]
`SyncHost` has a great deal of IO built into it; I am happier rolling my own, so I can be confident it's not going to unexpectedly hit the disk or network if I forget to pass a property or use it in an unexpected way or whatever. (Also I don't want any Node-specific builtins. I would like this to run on the web without having to shim anything.)

**Comment by rbuckton** [comment]
I created #49 to hook `resolveFile` which *should* remove any possible IO from the picture, so you would be able to do this:

```ts
let fakeHost = new SyncHost({ 
  useBuiltinGrammars: false,
  ignoreCase: false,
  resolveFile: file => file,
  readFileSync: file =>
    let idx = parseInt(file);
    if (idx.toString() !== file || idx < 0 || idx >= grammarParts.length) {
      throw new Error('tried to read non-existent ' + file);
    }
    return grammarParts[idx];
  },
  writeFileSync: false
});
```

That way if there's anything I ever need to add to `HostBase.prototype` et al you'll be able to pick it up automatically.

**Comment by rbuckton** [comment]
Alternatively, you can do this:

```ts
let fakeHost = new class extends SyncHost {
  readFileSync(file: string) {
    let idx = parseInt(file);
    if (idx.toString() !== file || idx < 0 || idx >= grammarParts.length) {
      throw new Error('tried to read non-existent ' + file);
    }
    return grammarParts[idx];
  }
  resolveFile(file: string) {
    return file;
  }
  normalizeFile(file: string) {
    return file;
  }
  getSourceFileSync(file: string) {
    return parser.parseSourceFile(file, this.readFileSync(file));
  }
};
```

**Comment by bakkot** [comment]
> I created #49 to hook `resolveFile` which _should_ remove any possible IO from the picture

I don't have enough confidence I will be able to use this correctly - if I fail to pass a method somewhere, now I'm hitting disk or network. I'm not comfortable using anything which falls back to doing actual IO instead of throwing. (Also it would still end up referencing Node's builtins, which I also don't want.)
