### ISSUE TITLE
Request: location information without leading whitepspace

### ISSUE THREAD

**Issue by bakkot** [rbuckton/grammarkdown#50]
Consider the following program:

```js
'use strict';

let gmd = require('.');

let host = gmd.SyncHost.forFile(`
  Foo :
    Bar
`);

let compilerOptions = {
  noChecks: false,
  noUnusedParameters: true,
};

let grammar = new gmd.Grammar([host.file], compilerOptions, host);
grammar.parseSync();

let file = grammar.sourceFiles[0];
let rhs = file.elements[0].body.elements[0];
let bar = rhs.head.symbol;
console.log(file.lineMap.positionAt(bar.pos));
```

This prints `{ line: 1, character: 7 }`: that is, it reports that the location for the `Bar` nonterminal begins following the colon, rather than at the `B`.

This is unexpected, at least to me: every parser on [astexplorer](https://astexplorer.net/#/gist/f4786e0d29387153382c9f3976275e58/1fb915e81618de1db97891bb2b0b034d5fe3f945) which reports location information (except, interestingly, TypeScript) gives locations which begin at the first non-whitespace character rather than including whitespace.

It is possible to work around this by instead using `console.log(file.lineMap.positionAt(bar.end - bar.name.text.length))`, but this is a bit awkward. Possibly there is some other API I should be using?

I've used a nonterminal for illustration, but the case I most care about currently is RightHandSide, because I'm trying to use this information to report errors and the location for a given RightHandSide typically points to the very end of the preceding one, which is confusing.

**Comment by rbuckton** [comment]
There's an exported function called `skipTrivia` that can do this for you:

```ts
...
const pos = gmd.skipTrivia(
  /*text*/ file.text,
  /*pos*/ bar.pos,
  /*end*/ file.text.length);

console.log(file.lineMap.positionAt(pos));
```

**Comment by rbuckton** [comment]
This is because trivia such as whitespace and `<ins>`/`<del>` tags are considered part of the node, so that you can be sure that the start/end positions all child elements (including synthetic trivia nodes for ins/del) are bounded by the start/end positions of the node.

**Comment by bakkot** [comment]
Ah, great, thanks.
