### ISSUE TITLE
Representing comments in the parse tree

### ISSUE THREAD

**Issue by bakkot** [rbuckton/grammarkdown#79]
I'm working on a [formatter](https://github.com/tc39/ecmarkup/issues/317) for ecmarkup, which implies formatting grammarkdown as well. Right now I can _almost_ just use the [grammarkdown emitter](https://github.com/rbuckton/grammarkdown/blob/01187ca51d63beded71e45d82d56727f5d7205f1/src/emitter/grammarkdown.ts) (with a little tweaking), but because the AST doesn't represent comments, those get stripped from the output.

Right now I'm working around it with a custom emitter which [scans](https://github.com/rbuckton/grammarkdown/blob/01187ca51d63beded71e45d82d56727f5d7205f1/src/scanner.ts#L992) every node for comments before emitting it, but that's a little painful.

Would it be possible to put comments in the parse tree directly, or have some other representation of them available without rescanning?

While I'm here: would it also be possible to accept HTML-style multiline comments? That's the style used in ecmarkup, being an HTML dialect, so it would be nice to be able to use them within grammarkdown snippets as well.

**Comment by rbuckton** [comment]
Published in `grammarkdown@3.2.0`
