### ISSUE TITLE
Is there a sanctioned way to reference a code point with its official name?

### ISSUE THREAD

**Issue by gibson042** [rbuckton/grammarkdown#91]
The [README](https://github.com/rbuckton/grammarkdown/blob/main/README.md#character-literals-and-ranges) mentions two ways to reference a Unicode code point, but fails to adequately specify them:

<blockquote>
<ul>
<li>An abbreviation for a Unicode Code point, of the form <code>&lt;NBSP&gt;</code></li>
<li>A Unicode code point, of the form <code>U+00A0</code></li>
</ul>
</blockquote>

[grammarkdown.grammar](https://github.com/rbuckton/grammarkdown/blob/main/spec/grammarkdown.grammar) doesn't mention the latter at all, and [implicitly defines the former](https://github.com/rbuckton/grammarkdown/blob/2ecf056a1b774733afd73113533dfad9f7ad44c8/spec/grammarkdown.grammar#L55-L62) as one or more non-`<` non-`>` non-|LineTerminator| code points in between `<` and `>`. As for the implementation, [scanner.ts uses `scanString(CharacterCodes.GreaterThan, …)`](https://github.com/rbuckton/grammarkdown/blob/2ecf056a1b774733afd73113533dfad9f7ad44c8/src/scanner.ts#L416), which pays special attention only to line terminators and `>`—and in particular _allows_ `<` when represented as a character reference like `&lt;` in e.g.
```
Nonterminal :::
  &lt;foo&lt;bar&gt;
```
[scanner.ts also handles the second form](https://github.com/rbuckton/grammarkdown/blob/main/src/scanner.ts#L509-L518) upon encountering "U+" or "u+" followed by four hexadecimal digits (and notably _not_ working for supplementary-plane characters such as U+1D306 TETRAGRAM FOR CENTRE "𝌆").

----

This is relevant because I want to express a nonterminal like `<U+2212 MINUS SIGN>`, which is not clearly valid or invalid according to documentation here and accepted by ecma262 `build:spec` while being rejected by esmeta (cf. https://github.com/tc39/ecma262/pull/3098/commits/cc5e203926bd54dc3e296915df0f9ca8a2e947aa and https://github.com/tc39/ecma262/actions/runs/5270397258/jobs/9529840136?pr=3098 ).

Ideally, we'd end up with alignment between documentation and implementation on a form that represents a single code point in any Unicode plane by its hexadecimal value _plus_ descriptive explanatory text (generally its name in the Unicode Character Database), e.g.
<blockquote>
<p>A single Unicode code point may be specified using one of the following forms:</p>
<ul>
<li><code>U+</code> followed by four to six non-lowercase hexadecimal digits with no leading zeroes other than those necessary for padding to a minimum of four digits, in accordance with <a href="https://www.unicode.org/versions/Unicode15.0.0/appA.pdf">The Unicode Standard, Version 15.0.0, Appendix A, Notational Conventions</a> (i.e., matching Unicode extended BNF pattern <code>"U+" ( [1-9 A-F] | "10" )? H H H H</code> or regular expression pattern <code>^U[+]([1-9A-F]|10)?[0-9A-F]{4}$</code> as in <code>U+00A0</code> or <code>U+1D306</code>)</li>
<li>The preceding representation followed by a space and a printable ASCII prose explanation (such as a character name) free of <code>&lt;</code> and <code>></code> and line terminators, all wrapped in <code>&lt;</code> and <code>></code> (i.e., matching Unicode extended BNF pattern <code>"&lt;" "U+" ( [1-9 A-F] | "10" )? H H H H " " [\u0020-\u007E -- [&lt;>]]+ ">"</code> or regular expression pattern <code>^&lt;U[+]([1-9A-F]|10)?[0-9A-F]{4} [\x20-\x3b\x3d\x3f-\x7e]+>$</code> as in <code>&lt;U+2212 MINUS SIGN></code>)</li>
<li>An abbreviation defined somewhere outside the grammar as an ASCII identifier name (i.e., matching Unicode extended BNF pattern <code>[A-Z a-z _] [A-Z a-z _ 0-9]*</code> or regular expression pattern <code>^[A-Za-z_][A-Za-z_0-9]*$</code> as in <code>&lt;NBSP></code>)</li>
</blockquote>

**Comment by rbuckton** [comment]
The `grammarkdown.grammar` file is fairly out of date, unfortunately, and is only used as part of tests at the moment. I'll look into updating the README.md to be a bit clearer on what is supported for unicode characters.

**Comment by gibson042** [comment]
> I have a fix inbound for 5 and 6 digit hexadecimal codes, as well as a fix to correctly disallow `<` (including HTML entity encoded `<`) inside of a `<>`-wrapped character literal.

:+1:

> Currently the `<>`-wrapped format just indicates some prose to dictate the character and there are no other restrictions to content aside from disallowing `<` and `>` without escaping using `\`. I left the `<>` format open-ended to be flexible with any other future consumer of `grammarkdown` that may chose to define characters in some other way.

Thanks for the clarification (which probably belongs in the README as well). That kind of generality can certainly be convenient, but it comes with costs (such as there being no reliable way for machines to consume `<…>` nonterminals). It also doesn't address what I'm looking for, which is a way to express a specific code point while _also_ providing an explanation for those poor souls who have not memorized the Unicode Character Database.

**Comment by rbuckton** [comment]
I can probably make `<>` a little stricter since a `>` on its own line can be used for any prose. That will probably end up as a separate fix than the one I'm working on now, though.

**Comment by rbuckton** [comment]
I have a fix for this in #91, although it does not include the more stringent parsing for `<>` just yet. I've called out the expected format that you suggested above in the README.md, however.

**Comment by rbuckton** [comment]
The fix in #92 now includes some validation for `<U+HHHH description>`

**Comment by rbuckton** [comment]
#92 now includes all of the rules you suggested.
